/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;

import Model.Logic.CarrierLogic;
import Model.Object.Carrier;
import javax.swing.JOptionPane;

/**
 *
 * @author tecno
 */
public class frmTransportadoraConsultar extends javax.swing.JInternalFrame {

    /**
     * Creates new form frmTransportadora
     */
    public frmTransportadoraConsultar() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtCarrierName = new javax.swing.JTextField();
        txtCarrierID = new javax.swing.JTextField();
        txtCarrierCNPJ = new javax.swing.JFormattedTextField();
        btnSearch = new javax.swing.JButton();
        btnChange = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        btnClear = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setTitle("Consultar/Alterar Transportadora");

        jLabel1.setText("Código:");

        jLabel2.setText("Nome:");

        jLabel3.setText("CNPJ:");

        try {
            txtCarrierCNPJ.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##.###.###/####-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        btnSearch.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Interface/search.png"))); // NOI18N
        btnSearch.setToolTipText("Procurar Transportadora");
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });

        btnChange.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Interface/save.png"))); // NOI18N
        btnChange.setToolTipText("Salvar Alterações");
        btnChange.setEnabled(false);
        btnChange.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChangeActionPerformed(evt);
            }
        });

        btnDelete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Interface/delete.png"))); // NOI18N
        btnDelete.setToolTipText("Excluir Transportadora");
        btnDelete.setEnabled(false);
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        btnClear.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Interface/clear.png"))); // NOI18N
        btnClear.setToolTipText("Limpar");
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(0, 364, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtCarrierID, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel1))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(txtCarrierCNPJ)))
                            .addComponent(txtCarrierName, javax.swing.GroupLayout.Alignment.LEADING))
                        .addGap(25, 25, 25))))
            .addGroup(layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addComponent(btnSearch)
                .addGap(18, 18, 18)
                .addComponent(btnChange)
                .addGap(18, 18, 18)
                .addComponent(btnDelete)
                .addGap(18, 18, 18)
                .addComponent(btnClear)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtCarrierName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCarrierID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCarrierCNPJ, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(btnSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnClear, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(btnChange)
                        .addComponent(btnDelete, javax.swing.GroupLayout.Alignment.TRAILING)))
                .addContainerGap(32, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void exibirMensagem(String str){
        JOptionPane.showMessageDialog(null, str);
    }

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        CarrierLogic logic = new CarrierLogic();
        Carrier carrier;
        if(!txtCarrierName.getText().equals("")){
            try{
                carrier = logic.searchByName(txtCarrierName.getText());
                txtCarrierID.setText(carrier.getCarrierId() + "");
                txtCarrierName.setText(carrier.getName());
                txtCarrierCNPJ.setText(carrier.getCNPJ());
                btnChange.setEnabled(true);
                btnDelete.setEnabled(true);
            } catch(Exception e) {
                exibirMensagem("Erro: Não foi realizar a pesquisa por transportadora.\n" + e.getMessage());
            }
        } else if(!txtCarrierID.getText().equals("")) {
            try {
                int y = Integer.parseInt(txtCarrierID.getText());
                carrier = logic.search(y);
                txtCarrierID.setText(carrier.getCarrierId() + "");
                txtCarrierName.setText(carrier.getName());
                txtCarrierCNPJ.setText(carrier.getCNPJ());
                btnChange.setEnabled(true);
                btnDelete.setEnabled(true);
            } catch(Exception e) {
                exibirMensagem("Erro: Não foi realizar a pesquisa por transportadora.\n" + e.getMessage());
            }
        } else {
            try {
                carrier = logic.searchByCNPJ(txtCarrierCNPJ.getText());
                txtCarrierID.setText(carrier.getCarrierId() + "");
                txtCarrierName.setText(carrier.getName());
                txtCarrierCNPJ.setText(carrier.getCNPJ());
                btnChange.setEnabled(true);
                btnDelete.setEnabled(true);
            } catch(Exception e) {
                exibirMensagem("Erro: Não foi realizar a pesquisa por transportadora.\n" + e.getMessage());
            }
        }
        this.revalidate();
    }//GEN-LAST:event_btnSearchActionPerformed

    private void btnChangeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChangeActionPerformed
        CarrierLogic logic = new CarrierLogic();
        try{
            logic.update(Integer.parseInt(txtCarrierID.getText()), txtCarrierName.getText(), txtCarrierCNPJ.getText());
            exibirMensagem("Transportadora alterada com sucesso.");
        } catch(Exception e) {
            exibirMensagem("Erro: Não foi possível alterar a transportadora.\n" + e.getMessage());
        }
    }//GEN-LAST:event_btnChangeActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        CarrierLogic logic = new CarrierLogic();
        try{
            logic.delete(Integer.parseInt(txtCarrierID.getText()));
            exibirMensagem("Transportadora deletada com sucesso.");
        } catch(Exception e) {
            exibirMensagem("Erro: Não foi possível deletar a transportadora.\n" + e.getMessage());
        }
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
        txtCarrierCNPJ.setText("");
        txtCarrierID.setText("");
        txtCarrierName.setText("");
        this.revalidate();
    }//GEN-LAST:event_btnClearActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnChange;
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnSearch;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JFormattedTextField txtCarrierCNPJ;
    private javax.swing.JTextField txtCarrierID;
    private javax.swing.JTextField txtCarrierName;
    // End of variables declaration//GEN-END:variables
}
