/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;

import Model.Logic.LoginLogic;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;

/**
 *
 * @author Lucas
 */
public class frmTelaLogin extends javax.swing.JInternalFrame {
    frmPrincipal jframe;

    /**
     * Creates new form frmTelaLogin
     */
    public frmTelaLogin() {
        initComponents();
    }
    
    public frmTelaLogin(frmPrincipal jframe) {
        initComponents();
        this.jframe = jframe;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        imgLogo = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtUserLogin = new javax.swing.JTextField();
        txtUserPassword = new javax.swing.JPasswordField();
        btnSignIn = new javax.swing.JButton();

        setIconifiable(true);
        setTitle("Realizar Login - Usuário/Vendedor");
        setFrameIcon(new javax.swing.ImageIcon(getClass().getResource("/Interface/icon.png"))); // NOI18N

        imgLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Interface/logoufc.png"))); // NOI18N
        imgLogo.setToolTipText("Universidade Federal do Ceará");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel2.setText("Usuário:");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel3.setText("Senha:");

        btnSignIn.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnSignIn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Interface/signup.png"))); // NOI18N
        btnSignIn.setText("Entrar");
        btnSignIn.setToolTipText("Entrar");
        btnSignIn.setDisabledIcon(null);
        btnSignIn.setDoubleBuffered(true);
        btnSignIn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSignInActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(243, 243, 243)
                        .addComponent(imgLogo))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(150, 150, 150)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel2)
                            .addComponent(txtUserLogin)
                            .addComponent(jLabel3)
                            .addComponent(txtUserPassword, javax.swing.GroupLayout.DEFAULT_SIZE, 235, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(225, 225, 225)
                        .addComponent(btnSignIn)))
                .addContainerGap(173, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(imgLogo)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtUserLogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtUserPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnSignIn)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSignInActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSignInActionPerformed
        //System.out.println(txtUserLogin.getText() + txtUserPassword.getText());
        LoginLogic login = new LoginLogic();
        if (txtUserLogin.getText().equals(""))
                  exibirMensagem("Digite o Usuário");
        else
        if (txtUserPassword.getText().equals(""))
                  exibirMensagem("Digite a Senha");
        else
            try {
                frmPrincipal parent = (frmPrincipal) SwingUtilities.getWindowAncestor(this);
                parent.setLoggedUser(login.Login(txtUserLogin.getText(), txtUserPassword.getText()));
                parent.displayMenu();
                this.dispose();
            } catch (Exception e){
                    exibirMensagem(e.getMessage());
                }
                this.revalidate();
    }//GEN-LAST:event_btnSignInActionPerformed

    public void exibirMensagem(String str){
        JOptionPane.showMessageDialog(null, str);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSignIn;
    private javax.swing.JLabel imgLogo;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField txtUserLogin;
    private javax.swing.JPasswordField txtUserPassword;
    // End of variables declaration//GEN-END:variables
}
