/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;

import Model.Logic.UserLogic;
import Model.Object.User;
import javax.swing.JOptionPane;

/**
 *
 * @author Lucas
 */
public class frmUsuarioVendedorPainel extends javax.swing.JInternalFrame {
    private final User loggedUser;

    /**
     * Creates new form CadastroUsuarioVendedor
     * @param loggedUser
     */
    public frmUsuarioVendedorPainel(User loggedUser) {
        initComponents();
        this.loggedUser = loggedUser;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtSellerName = new javax.swing.JTextField();
        txtSellerCPF = new javax.swing.JFormattedTextField();
        txtSellerPhone = new javax.swing.JFormattedTextField();
        txtSellerBirthday = new javax.swing.JFormattedTextField();
        txtUserLogin = new javax.swing.JTextField();
        txtUserPassword = new javax.swing.JPasswordField();
        btnSignUp = new javax.swing.JButton();
        btnSearch = new javax.swing.JButton();
        btnChange = new javax.swing.JButton();
        btnClear = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Painel de Controle - Usuário/Vendedor");

        jLabel1.setText("Nome Completo:");

        jLabel2.setText("CPF:");

        jLabel3.setText("Telefone:");

        jLabel4.setText("Data de nascimento:");

        jLabel5.setText("Usuário de acesso:");

        jLabel6.setText("Senha:");

        txtSellerName.setToolTipText("");

        try {
            txtSellerCPF.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        try {
            txtSellerPhone.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##)#####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        try {
            txtSellerBirthday.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        btnSignUp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Interface/signup.png"))); // NOI18N
        btnSignUp.setToolTipText("Cadastrar Vendedor");
        btnSignUp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSignUpActionPerformed(evt);
            }
        });

        btnSearch.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Interface/search.png"))); // NOI18N
        btnSearch.setToolTipText("Consultar Vendedor");
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });

        btnChange.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Interface/edit.png"))); // NOI18N
        btnChange.setToolTipText("Salvar Alterações");
        btnChange.setEnabled(false);
        btnChange.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChangeActionPerformed(evt);
            }
        });

        btnClear.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Interface/clear.png"))); // NOI18N
        btnClear.setToolTipText("Limpar");
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });

        btnDelete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Interface/delete.png"))); // NOI18N
        btnDelete.setToolTipText("Deletar");
        btnDelete.setEnabled(false);
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtSellerName, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(txtSellerCPF, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 110, Short.MAX_VALUE)
                                .addComponent(txtSellerPhone, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtSellerBirthday, javax.swing.GroupLayout.Alignment.LEADING))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(txtUserLogin, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtUserPassword, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 175, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(65, 65, 65)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnSignUp)
                                .addGap(18, 18, 18)
                                .addComponent(btnSearch)
                                .addGap(18, 18, 18)
                                .addComponent(btnChange))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(44, 44, 44)
                                .addComponent(btnClear)
                                .addGap(18, 18, 18)
                                .addComponent(btnDelete)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtSellerName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtSellerCPF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtSellerPhone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtSellerBirthday, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtUserLogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtUserPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnSearch)
                    .addComponent(btnChange)
                    .addComponent(btnSignUp))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnDelete)
                    .addComponent(btnClear))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        txtSellerName.getAccessibleContext().setAccessibleName("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
        txtSellerName.setText("");
        txtSellerCPF.setText("");
        txtSellerPhone.setText("");
        txtSellerBirthday.setText("");
        txtUserLogin.setText("");
        txtUserPassword.setText("");
        btnChange.setEnabled(false);
        btnDelete.setEnabled(false);
        this.revalidate();
    }//GEN-LAST:event_btnClearActionPerformed

    private void btnChangeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChangeActionPerformed
        UserLogic controller = new UserLogic();
        try{
            controller.Update(txtSellerName.getText(), txtSellerCPF.getText(), txtSellerPhone.getText(), txtSellerBirthday.getText(), txtUserLogin.getText(), txtUserPassword.getText());
            exibirMensagem("Usuário alterado com sucesso.");
        } catch(Exception e) {
            exibirMensagem("Erro: Não foi possível alterar o usuário.\n" + e.getMessage());
        }
    }//GEN-LAST:event_btnChangeActionPerformed

    private void btnSignUpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSignUpActionPerformed
        UserLogic controller = new UserLogic();
        try{
            controller.SignUp(txtSellerName.getText(), txtSellerCPF.getText(), txtSellerPhone.getText(), txtSellerBirthday.getText(), txtUserLogin.getText(), txtUserPassword.getText(), loggedUser);
            exibirMensagem("Usuário cadastrado com sucesso.");
        } catch(Exception e) {
            exibirMensagem("Erro: Não foi possível cadastrar o usuário.\n" + e.getMessage());
        }
    }//GEN-LAST:event_btnSignUpActionPerformed

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        UserLogic controller = new UserLogic();

        if (!"".equals(txtSellerName.getText())) {
            try {
                User user = controller.SearchName(txtSellerName.getText());
                txtSellerName.setText(user.getName());
                txtSellerCPF.setText(user.getCPF());
                txtSellerPhone.setText(user.getPhone());

                String dt1 = user.getBirthday().toString();
                String dt2 = dt1.substring(8, 10) + "/" +
                        dt1.substring(5, 7)+ "/" +
                        dt1.substring(0, 4);
                txtSellerBirthday.setText(dt2);

                txtUserLogin.setText(user.getUsername());
                txtUserPassword.setText(user.getPassword());

                btnChange.setEnabled(true);
                btnDelete.setEnabled(true);
            } catch(Exception e) {
                exibirMensagem("Erro: Falha na pesquisa do usuário.\n" + e.getMessage());
            }
        } else {
            try {
                User user = controller.Search(txtSellerCPF.getText());
                txtSellerName.setText(user.getName());
                txtSellerCPF.setText(user.getCPF());
                txtSellerPhone.setText(user.getPhone());

                String dt1 = user.getBirthday().toString();
                String dt2 = dt1.substring(8, 10) + "/" +
                        dt1.substring(5, 7)+ "/" +
                        dt1.substring(0, 4);
                txtSellerBirthday.setText(dt2);

                txtUserLogin.setText(user.getUsername());
                txtUserPassword.setText(user.getPassword());

                btnChange.setEnabled(true);
                btnDelete.setEnabled(true);
            } catch(Exception e) {
                exibirMensagem("Erro: Falha na pesquisa do usuário.\n" + e.getMessage());
            }
        }
    }//GEN-LAST:event_btnSearchActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        UserLogic logic = new UserLogic();
        try{
            logic.Delete(txtSellerName.getText(), txtSellerCPF.getText(), txtSellerPhone.getText(), txtSellerBirthday.getText(), txtUserLogin.getText(), txtUserPassword.getText());
            exibirMensagem("Usuário deletado com sucesso.");
        } catch(Exception e) {
            exibirMensagem("Erro: Não foi possível deletar o usuário.\n" + e.getMessage());
        }
    }//GEN-LAST:event_btnDeleteActionPerformed

    public void exibirMensagem(String str){
        JOptionPane.showMessageDialog(null, str);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnChange;
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnSearch;
    private javax.swing.JButton btnSignUp;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JFormattedTextField txtSellerBirthday;
    private javax.swing.JFormattedTextField txtSellerCPF;
    private javax.swing.JTextField txtSellerName;
    private javax.swing.JFormattedTextField txtSellerPhone;
    private javax.swing.JTextField txtUserLogin;
    private javax.swing.JPasswordField txtUserPassword;
    // End of variables declaration//GEN-END:variables
}
